### ISSUE TITLE
Why not fork 

### ISSUE THREAD

**Issue by Shnoulle** [leandrobhbr/ShibbolethAuthLimeSurvey#1]
Why you didn't fork https://github.com/atlet/LimeSurvey-ShibbolethAuth directly ?

really more easy to follow with fork …

**Comment by leandrobhbr** [comment]
Hi Denis,

Yes it would be easier. Thanks for the source: https://github.com/atlet/LimeSurvey-ShibbolethAuth

But, I think the limesurvey needs both versions:

1) I adapted it for version 4 of LimeSurvey. My code doesn't work in version 3.
2) I changed the source code a lot, and i need change this methods: beforeLogin() , init() and comments for the test developer.
3) I want to publish in the limestory and help the community (https://account.limesurvey.org/limestore)
4) This update was an old request on the forum, and nobody had done (https://forums.limesurvey.org/forum/plugins/118829-shibboleth,-anybody-doing/198674?start=0)

regards

Leandro

**Comment by Shnoulle** [comment]
It's not both version or not, but you loose all commit history and author … 

It's a fork or not ? If yes : why you didn't fork it on github directly …

I think we can always do some non limited version : have a version for 3 and 4 (i have some plugin working since 2.05, you can even use php version_compare function etc …)
