### ISSUE TITLE
How can I use a different Authentication Method for Remotecontrol API (LSRC2)

### ISSUE THREAD

**Issue by OliverTUBAF** [leandrobhbr/ShibbolethAuthLimeSurvey#3]
Dear All,

unfortunately I cannot find any JSON RPC Client, that can handle Shibboleth logins, therefore I like to use the remote control API with a different authentication plugin. My first try was to trigger a fallback to the default Authdb, with no success. I used the following apache config:

```
# Backend with Shibboleth
<Location /admin>
	AuthType shibboleth
	ShibRequireSession On
	require valid-user
</Location>

<Location />
	AuthType shibboleth
	ShibRequestSetting requireSession false
	ShibUseHeaders On
	Require shibboleth
</Location>

# Remotecontrol without Shibboleth
<Location /admin/remotecontrol>
	AuthType None
</Location>
```

The API responds then to valid credentials from Authdb with "Invalid user name or password". If I disable Sibboleth completely, the credentials work and I receive a session key. So there is nothing wrong with my credentials themself.

Thank you in advance!

**Comment by Shnoulle** [comment]
Totally unrelated to Shibboleth mode since Shibboleth can not be used automatically by a server.

https://gitlab.com/SondagesPro/Authentification/AuthRemoteToken

**Comment by OliverTUBAF** [comment]
Thank you very much for that hint, this really helped me! I searched the internet multiple days for such a solution, but could not find one.
